version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    build:
      context: .
      dockerfile: ./DBDOCKERFILE
    expose:
      - 3306
    ports:
      - "3456:3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./dev.env
volumes:
  data: