version: '3.9'

services:

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - 5173
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    expose:
      - 8080
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    build:
      context: backend
      dockerfile: backend/DBDockefile
    expose:
      - 3306
    ports:
      - "3456:3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - backend/dev.env

volumes:
  data: