spring.application.name=achlearnment

#spring.datasource.url=jdbc:mariadb://db:3306/achlearnment
#spring.datasource.username=admin
#spring.datasource.password=secretdevpass123

spring.datasource.url=jdbc:mariadb://127.0.0.1:3456/achlearnment
spring.datasource.username=admin
spring.datasource.password=secretdevpass123

genai.groq.apikey=${GROQ_API_KEY}

genai.settings.speech-to-text.model=whisper-large-v3-turbo
genai.settings.structured-outputs.model=moonshotai/kimi-k2-instruct-0905
genai.settings.structured-outputs.prompt=You are an english teacher who is listening to a student talking about a certain topic, \
  which will be given at the end of this prompt. \
  Create mistakes overview no longer than 200 words, \
  give student advice(200 words max) what to do to fix those mistakes \
  and check if the user was talking on topic, \
  don't be very strict about the topic checking. \
  Don't use formatting like bullet points, arrows, codeblocks; you can only use plain text. \
  Don't look at the punctuation in the given text, treat given text as if it was spoken to you. \
  Output JSON only using the schema provided.

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#springdoc.api-docs.path=/docs